"""add book tags table-new

Revision ID: daddfaae6a99
Revises: d76e5bf6b9b3
Create Date: 2024-10-13 22:00:02.620976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'daddfaae6a99'
down_revision: Union[str, None] = 'd76e5bf6b9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
